
version: '3.8'

services:
  airflow:
    build:
      context: .
      dockerfile: airflow/Dockerfile
    image: custom-airflow:latest
    restart: always
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__CORE__FERNET_KEY: your_fernet_key_here
      AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: 'false'
      AIRFLOW__CORE__LOAD_EXAMPLES: 'false'
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: sqlite:////usr/local/airflow/airflow.db
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./pipeline:/opt/airflow/pipeline
      - ./mlflow:/mlflow
    ports:
      - "8080:8080"
    command: bash -c "airflow db init && airflow users create \
                      --username admin \
                      --firstname Firstname \
                      --lastname Lastname \
                      --role Admin \
                      --email admin@example.org \
                      --password admin && \
                      airflow scheduler & airflow webserver"
    depends_on:
      - mlflow

  mlflow:
    image: ghcr.io/mlflow/mlflow:v2.12.1
    ports:
      - "5000:5000"
    volumes:
      - ./mlflow:/mlflow
    command: mlflow server --host 0.0.0.0 --backend-store-uri sqlite:///mlflow/mlflow.db --default-artifact-root /mlflow/artifacts
