version: '3.8'

services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: mlflow
      POSTGRES_PASSWORD: mlflow
      POSTGRES_DB: mlflow
    volumes:
      - postgres-data:/var/lib/postgresql/data

  mlflow:
    image: ghcr.io/mlflow/mlflow:latest
    environment:
      BACKEND_STORE_URI: postgresql://mlflow:mlflow@postgres/mlflow
      ARTIFACT_ROOT: /mlflow/artifacts
    command: mlflow server \
      --backend-store-uri postgresql://mlflow:mlflow@postgres/mlflow \
      --default-artifact-root /mlflow/artifacts \
      --host 0.0.0.0
    ports:
      - "5000:5000"
    volumes:
      - ./mlflow:/mlflow
    depends_on:
      - postgres

  airflow:
    image: apache/airflow:2.9.1
    restart: always
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__CORE__FERNET_KEY: your_fernet_key_here
      AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: 'false'
      AIRFLOW__CORE__LOAD_EXAMPLES: 'false'
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: sqlite:////usr/local/airflow/airflow.db
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./pipeline:/opt/airflow/pipeline
      - ./mlflow:/mlflow  # To share model artifacts
    ports:
      - "8080:8080"
    command: bash -c "airflow db init && airflow users create \
                      --username admin \
                      --firstname Firstname \
                      --lastname Lastname \
                      --role Admin \
                      --email admin@example.org \
                      --password admin && \
                      airflow scheduler & airflow webserver"
    depends_on:
      - mlflow

volumes:
  postgres-data:
